#!/usr/bin/env python3
"""
Phase 8: Streamlit Dashboard for the AI Finance Controller.

Reads reconciliation_report.json, metrics_report.json, and audit_trail.md
(all cached via @st.cache_data). Calls qa_agent.answer_question() only
on user question submission (the one live/dynamic part).

Run: streamlit run dashboard.py
"""

import json
import hashlib
import sys
import os
from pathlib import Path
from collections import Counter

import streamlit as st

# ── Paths ────────────────────────────────────────────────────────────
ROOT = Path(__file__).resolve().parent
RR_PATH = ROOT / "engine" / "output" / "reconciliation_report.json"
MR_PATH = ROOT / "engine" / "output" / "metrics_report.json"
AUDIT_PATH = ROOT / "audit_trail.md"

# Ensure agent/ is importable for qa_agent
sys.path.insert(0, str(ROOT / "agent"))


# ── Data loading (cached) ───────────────────────────────────────────
@st.cache_data
def load_data():
    """Load static JSON data once, cached across Streamlit reruns.

    audit_trail.md is intentionally NOT cached here: the file is
    regenerated by engine/generate_audit.py and Streamlit never notices
    external .md changes, so a stale copy could keep showing old content.
    """
    with open(RR_PATH, "r", encoding="utf-8") as f:
        rr = json.load(f)
    with open(MR_PATH, "r", encoding="utf-8") as f:
        mr = json.load(f)
    return rr, mr


@st.cache_data
def compute_hashes():
    """Compute SHA-256 hashes of key files for the footer."""
    files = {
        "match_log": ROOT / "engine" / "output" / "match_log.json",
        "reconciliation_report": RR_PATH,
        "metrics_report": MR_PATH,
        "explanations": ROOT / "agent" / "output" / "explanations.json",
        "audit_trail": AUDIT_PATH,
    }
    hashes = {}
    for name, path in files.items():
        if path.exists():
            with open(path, "rb") as _f: h = hashlib.sha256(_f.read()).hexdigest()[:16]
            hashes[name] = h
    return hashes


# ── Page config ──────────────────────────────────────────────────────
st.set_page_config(
    page_title="AI Finance Controller",
    page_icon="🏦",
    layout="wide",
)

# ── Custom CSS: Fintech theme ────────────────────────────────────────
st.markdown("""
<style>
/* ── Hide Streamlit chrome ────────────────────────────────────── */
#MainMenu {visibility: hidden;}
header[data-testid="stHeader"] {background: transparent;}
footer {visibility: hidden;}
div[data-testid="stDecoration"] {display: none;}

/* ── Global overrides ─────────────────────────────────────────── */
.stApp {
background: linear-gradient(180deg, #0a0e1a 0%, #0f1629 100%);
color: #e0e6f0;
}
.stApp > header {
background: transparent;
}

/* ── Title styling ────────────────────────────────────────────── */
h1 {
color: #ffffff !important;
font-weight: 700 !important;
letter-spacing: -0.5px;
padding-bottom: 0.2rem;
}

/* ── Section headers ──────────────────────────────────────────── */
h2, .stSubheader {
color: #c8d6e5 !important;
font-weight: 600 !important;
border-bottom: 2px solid #2d3a5c;
padding-bottom: 0.3rem;
margin-top: 1.5rem;
}

/* ── Metric cards ─────────────────────────────────────────────── */
div[data-testid="stMetric"] {
background: linear-gradient(135deg, #141b2d 0%, #1a2340 100%);
border: 1px solid #2d3a5c;
border-left: 4px solid #4f8cff;
border-radius: 10px;
padding: 1rem 1.2rem;
margin: 0.3rem 0;
box-shadow: 0 2px 8px rgba(0,0,0,0.3);
transition: border-color 0.2s;
}
div[data-testid="stMetric"]:hover {
border-left-color: #7ab3ff;
}
/* Level 2 legend cards are the only st.metric elements on the page:
   teal/amber/red stripe per outcome (Phase 14 card restoration). */
div[data-testid="stHorizontalBlock"] > div[data-testid="stColumn"]:nth-child(1) div[data-testid="stMetric"] { border-left-color: #00d2a0 !important; }
div[data-testid="stHorizontalBlock"] > div[data-testid="stColumn"]:nth-child(1) div[data-testid="stMetric"]:hover { border-left-color: #00e8b3 !important; }
div[data-testid="stHorizontalBlock"] > div[data-testid="stColumn"]:nth-child(2) div[data-testid="stMetric"] { border-left-color: #f5a623 !important; }
div[data-testid="stHorizontalBlock"] > div[data-testid="stColumn"]:nth-child(2) div[data-testid="stMetric"]:hover { border-left-color: #f7b93d !important; }
div[data-testid="stHorizontalBlock"] > div[data-testid="stColumn"]:nth-child(3) div[data-testid="stMetric"] { border-left-color: #ff6b6b !important; }
div[data-testid="stHorizontalBlock"] > div[data-testid="stColumn"]:nth-child(3) div[data-testid="stMetric"]:hover { border-left-color: #ff8585 !important; }

div[data-testid="stMetric"] label {
color: #8899b0 !important;
font-size: 0.85rem !important;
font-weight: 500 !important;
text-transform: uppercase;
letter-spacing: 0.5px;
}
div[data-testid="stMetric"] div[data-testid="stMetricValue"] {
color: #ffffff !important;
font-size: 1.8rem !important;
font-weight: 700 !important;
}
div[data-testid="stMetric"] div[data-testid="stMetricDelta"] {
font-weight: 600 !important;
}

/* ── Divider styling ──────────────────────────────────────────── */
hr {
border: none;
border-top: 1px solid #1e2a45;
margin: 1.2rem 0;
}

/* ── Table / DataFrame styling ────────────────────────────────── */
div[data-testid="stDataFrame"] {
border: 1px solid #2d3a5c;
border-radius: 8px;
overflow: hidden;
}
div[data-testid="stDataFrame"] table {
background: #111827;
}
div[data-testid="stDataFrame"] th {
background: #1a2340 !important;
color: #8899b0 !important;
font-weight: 600 !important;
text-transform: uppercase;
font-size: 0.75rem !important;
letter-spacing: 0.5px;
}
div[data-testid="stDataFrame"] td {
color: #c8d6e5 !important;
border-color: #1e2a45 !important;
}

/* ── Input fields ─────────────────────────────────────────────── */
div[data-testid="stTextInput"] input,
div[data-testid="stTextArea"] textarea,
div[data-testid="stSelectbox"] div[data-baseweb="select"] {
background: #141b2d !important;
border-color: #2d3a5c !important;
color: #e0e6f0 !important;
}
div[data-testid="stTextInput"] input:focus,
div[data-testid="stTextArea"] textarea:focus {
border-color: #4f8cff !important;
box-shadow: 0 0 0 1px #4f8cff;
}

/* ── Buttons ──────────────────────────────────────────────────── */
.stButton > button {
background: linear-gradient(135deg, #4f8cff 0%, #3a6fd8 100%) !important;
color: #ffffff !important;
border: none !important;
border-radius: 8px !important;
font-weight: 600 !important;
padding: 0.4rem 1.5rem !important;
transition: all 0.2s !important;
box-shadow: 0 2px 6px rgba(79,140,255,0.3);
}
.stButton > button:hover {
background: linear-gradient(135deg, #6ba3ff 0%, #4f8cff 100%) !important;
box-shadow: 0 4px 12px rgba(79,140,255,0.4);
transform: translateY(-1px);
}

/* ── Expander styling ─────────────────────────────────────────── */
div[data-testid="stExpander"] {
background: #141b2d;
border: 1px solid #2d3a5c;
border-radius: 8px;
}
div[data-testid="stExpander"] summary {
color: #c8d6e5 !important;
font-weight: 600 !important;
}

/* ── Chat messages (Q&A) ──────────────────────────────────────── */
div[data-testid="stChatMessage"] {
background: #141b2d;
border-radius: 10px;
border: 1px solid #1e2a45;
padding: 0.8rem 1rem;
margin: 0.3rem 0;
}

/* ── Warning/info boxes ───────────────────────────────────────── */
div[data-testid="stAlert"] {
border-radius: 8px;
border-left-width: 4px;
}

/* ── Caption / help text ──────────────────────────────────────── */
.stCaption, small, .stMarkdown small {
color: #6b7c93 !important;
}

/* ── Scrollbar styling ────────────────────────────────────────── */
::-webkit-scrollbar { width: 6px; }
::-webkit-scrollbar-track { background: #0a0e1a; }
::-webkit-scrollbar-thumb { background: #2d3a5c; border-radius: 3px; }
::-webkit-scrollbar-thumb:hover { background: #4f8cff; }

/* ── Vega chart container ─────────────────────────────────────── */
div[data-testid="stVegaLiteChart"] {
background: #111827;
border-radius: 8px;
padding: 0.5rem;
border: 1px solid #1e2a45;
}
/* ── Phase 9: Top-level hierarchy (DESIGN_PHASE9_FRONTEND.md) ── */
.scale-value {
font-size: 3.2rem;
font-weight: 700;
color: #ffffff;
letter-spacing: -1px;
line-height: 1.05;
}
.scale-label {
font-size: 0.78rem;
text-transform: uppercase;
letter-spacing: 0.12em;
color: #8899b0;
margin-top: 0.3rem;
}
.scale-sub {
font-size: 0.9rem;
color: #6b7c93;
margin-top: 0.15rem;
}
.micro-label {
font-size: 0.72rem;
text-transform: uppercase;
letter-spacing: 0.12em;
color: #8899b0;
margin-bottom: 0.5rem;
}
.seg-bar {
display: flex;
width: 100%;
height: 12px;
border-radius: 6px;
overflow: hidden;
background: #1a2340;
}
.seg { height: 100%; }
.seg-teal { background-color: #00d2a0; }
.seg-amber { background-color: #f5a623; }
.seg-red { background-color: #ff6b6b; }
/* ── Phase 14: restored card containment (visual only) ──────────
   Mirrors the original st.metric card depth: gradient fill, border,
   left accent stripe, radius, shadow. Used by Level 1 / 2 / 4. */
.hcard {
background: linear-gradient(135deg, #141b2d 0%, #1a2340 100%);
border: 1px solid #2d3a5c;
border-left: 4px solid #4f8cff;
border-radius: 10px;
padding: 1rem 1.2rem;
margin: 0.4rem 0;
box-shadow: 0 2px 8px rgba(0,0,0,0.3);
}
.verify-block {
display: flex;
align-items: baseline;
gap: 0.7rem;
margin-top: 0.35rem;
}
.verify-value {
font-size: 1.6rem;
font-weight: 600;
color: #ffffff;
}
.verify-label {
font-size: 0.85rem;
color: #8899b0;
}
.disclaimer {
font-size: 0.75rem;
color: #6b7c93;
line-height: 1.5;
}

/* ── Phase 10: Case detail card (DESIGN_PHASE10_CASE_EXPLORER.md) ── */
.detail-card {
border: 1px solid #2d3a5c;
border-radius: 10px;
padding: 0.9rem 1.1rem;
background: #111827;
margin-top: 0.4rem;
}
.detail-head {
display: flex;
flex-wrap: wrap;
align-items: center;
gap: 0.7rem;
padding-bottom: 0.55rem;
border-bottom: 1px solid #1e2a45;
margin-bottom: 0.5rem;
}
.pill {
display: inline-block;
padding: 0.12rem 0.6rem;
border-radius: 999px;
font-size: 0.7rem;
font-weight: 600;
letter-spacing: 0.06em;
text-transform: uppercase;
border: 1px solid transparent;
}
.pill-green { color: #00d2a0; background: rgba(0, 210, 160, 0.12); border-color: rgba(0, 210, 160, 0.45); }
.pill-amber { color: #f5a623; background: rgba(245, 166, 35, 0.12); border-color: rgba(245, 166, 35, 0.45); }
.pill-red   { color: #ff6b6b; background: rgba(255, 107, 107, 0.12); border-color: rgba(255, 107, 107, 0.45); }
.badge {
display: inline-block;
padding: 0.12rem 0.6rem;
border-radius: 6px;
background: rgba(79, 140, 255, 0.14);
color: #7ab3ff;
font-size: 0.72rem;
font-weight: 600;
letter-spacing: 0.04em;
}
.ev-section { margin-top: 1rem; }
.evidence-row {
display: flex;
gap: 1.2rem;
padding: 0.18rem 0;
border-bottom: 1px solid #1a2340;
font-size: 0.9rem;
line-height: 1.5;
}
.evidence-row:last-child { border-bottom: none; }
.ev-label {
color: #8899b0;
min-width: 240px;
max-width: 46%;
flex-shrink: 0;
}
.ev-value {
color: #c8d6e5;
word-break: break-word;
}
.what-line {
color: #e0e6f0;
font-size: 0.95rem;
line-height: 1.55;
margin-top: 0.15rem;
}

</style>
""", unsafe_allow_html=True)

# ── Load data ────────────────────────────────────────────────────────
rr, mr = load_data()
# Read audit_trail.md fresh each run (not cached - see load_data docstring)
with open(AUDIT_PATH, "r", encoding="utf-8") as _f:
    audit_text = _f.read()
hashes = compute_hashes()

# Merge all cases into one list
all_cases = rr.get("orders", []) + rr.get("settlements", [])
# Shared case-detail code table, used by the Phase 2 case-detail card.
from html import escape as _esc

_CODE_INFO = {
    "CURRENCY_MISMATCH": ("Currency conversion mismatch", "Order and settlement amounts differ before FX; equal after the recorded FX rate."),
    "REFUND_SPLIT": ("Refund split across cycles", "Refund spans settlement batch boundaries; expected behavior."),
    "UNRECORDED_REFUND": ("Refund not recorded in settlement", "Ledger shows a refund with no matching refund deduction in settlement rows."),
    "DUPLICATE_ORDER": ("Duplicate order suspected", "Conflicting gross amounts suggest a possible duplicate order entry."),
    "UNMATCHED_ORDER": ("No matching settlement credit", "No settlement row could be matched to this order."),
    "GHOST_TRANSACTION": ("Bank credit with no matching order", "Settlement contains an order_id not present in the ledger."),
    "NEFT_FAILED": ("NEFT settlement failed", "Batch was settled via NEFT and the credit did not arrive."),
    "NO_CREDIT_EXPECTED": ("No credit expected for batch", "Batch net is negative; no bank credit was expected."),
}

# ── Header ────────────────────────────────────────────────────────────
st.title("AI Finance Controller")
st.caption(
    "Deterministic multi-source reconciliation of orders, payments and "
    "settlements, narrated by a grounded AI layer"
)
st.divider()


# ----------------------------------------------------------------------
# SECTION A: Top-Level Hierarchy (DESIGN_PHASE9_FRONTEND.md)
# ----------------------------------------------------------------------
summary = rr.get("summary", {})
overall = summary.get("overall", {})
mr_overall = mr.get("overall", {})

_total = overall.get("total_cases", 0)
_reconciled = overall.get("reconciled_total", 0)
_review = overall.get("needs_human_review_total", 0)
_unresolved = overall.get("unresolved_total", 0)
_orders_sum = summary.get("orders", {})
_settlements_sum = summary.get("settlements", {})

# ── Level 1: Scale ────────────────────────────────────────────────────
st.markdown(
    f"""
    <div class="hcard" style="border-left-color: #00d2a0;">
      <div class="scale-value">{_total:,}</div>
      <div class="scale-label">CASES PROCESSED</div>
      <div class="scale-sub">{_orders_sum.get("total", 0)} orders | {_settlements_sum.get("total", 0)} settlements</div>
    </div>
    """,
    unsafe_allow_html=True,
)

# ── Level 2: Outcome ──────────────────────────────────────────────────
# Tooltip (title attribute) copy, per DESIGN_PHASE9_FRONTEND.md section 3.
_tip_rec = (
    f"{_reconciled} cases resolved without human intervention: "
    f"{_orders_sum.get('reconciled', 0) + _settlements_sum.get('reconciled', 0)} plain matches, "
    f"{_orders_sum.get('reconciled_with_note', 0)} reconciled with an explanatory note, "
    f"{_settlements_sum.get('reconciled_no_credit_due', 0)} no-credit-due settlement."
)
_rev_s = _settlements_sum.get("needs_human_review", 0)
_unres_s = _settlements_sum.get("unresolved", 0)
_tip_rev = (
    f"Genuinely ambiguous cases flagged for human judgment - "
    f"{_orders_sum.get('needs_human_review', 0)} orders, "
    f"{_rev_s} {'settlement' if _rev_s == 1 else 'settlements'}."
)
_tip_un = (
    f"Cases where no match was possible - escalation required. "
    f"{_orders_sum.get('unresolved', 0)} orders, "
    f"{_unres_s} {'settlement' if _unres_s == 1 else 'settlements'}."
)

st.markdown(
    f"""
    <div class="micro-label" style="margin-top: 1.5rem;">OUTCOME</div>
    <div class="hcard" style="border-left-color: #4f8cff;">
      <div class="seg-bar">
        <div class="seg seg-teal" style="width: {_reconciled / _total * 100:.2f}%;" title="{_tip_rec}"></div>
        <div class="seg seg-amber" style="width: {_review / _total * 100:.2f}%;" title="{_tip_rev}"></div>
        <div class="seg seg-red" style="width: {_unresolved / _total * 100:.2f}%;" title="{_tip_un}"></div>
      </div>
    </div>
    """,
    unsafe_allow_html=True,
)

# Legend callouts as native st.metric cards (restores the original card depth)
_leg1, _leg2, _leg3 = st.columns(3)
_leg1.metric("Reconciled", f"{_reconciled:,}", f"{_reconciled / _total:.1%}",
             delta_color="off", help=_tip_rec)
_leg2.metric("Needs review", f"{_review:,}", f"{_review / _total:.1%}",
             delta_color="off", help=_tip_rev)
_leg3.metric("Unresolved", f"{_unresolved:,}", f"{_unresolved / _total:.1%}",
             delta_color="off", help=_tip_un)

# ── Level 3: Attention detail ─────────────────────────────────────────
st.subheader("Cases Needing Attention")
st.caption(
    f"{_review + _unresolved} of {_total} cases flagged "
    f"({(_review + _unresolved) / _total:.1%}) - the system correctly "
    "surfaced these instead of guessing; none is a hidden failure."
)

# Chart: Exception cases only (plain 562 dwarfs the others, so show meaningful variation)
status_counts = Counter(e["simplified_status"] for e in all_cases)

# Short labels for chart readability (fixed logical order, horizontal bars)
import pandas as pd
chart_labels = ["With Note", "No Credit Due", "Review", "Unresolved"]
chart_keys = [
    "Reconciled (with note)",
    "Reconciled (no credit due)",
    "Needs Human Review",
    "Unresolved",
]
chart_values = [status_counts.get(k, 0) for k in chart_keys]
chart_df = pd.DataFrame({"Category": chart_labels, "Count": chart_values})
chart_df["Category"] = pd.Categorical(
    chart_df["Category"], categories=chart_labels, ordered=True
)

total_chart = sum(status_counts.values())

# Render horizontal bar chart via raw Vega-Lite spec for reliable orientation.
# st.altair_chart(use_container_width=True) overrides Altair's width settings,
# which breaks horizontal bar charts. A raw Vega-Lite spec avoids this.
vlt = {
    "$schema": "https://vega.github.io/schema/vega-lite/v5.json",
    "width": "container",
    "height": 140,
    "data": {
        "values": [
            {"Category": chart_labels[i], "Count": chart_values[i]}
            for i in range(len(chart_labels))
        ]
    },
    "mark": {"type": "bar", "cornerRadiusEnd": 4},
    "encoding": {
        "y": {
            "field": "Category",
            "type": "nominal",
            "sort": chart_labels,
            "axis": {"labelAngle": 0, "title": None}
        },
        "x": {
            "field": "Count",
            "type": "quantitative",
            "axis": {"tickMinStep": 1, "title": None}
        },
        "tooltip": [
            {"field": "Category", "type": "nominal"},
            {"field": "Count", "type": "quantitative"}
        ],
        "color": {
            "field": "Category",
            "type": "nominal",
            "scale": {
                "domain": ["With Note", "No Credit Due", "Review", "Unresolved"],
                "range": ["#00d2a0", "#00d2a0", "#f5a623", "#ff6b6b"]
            },
            "legend": None
        }
    },
    "config": {"view": {"stroke": None}, "axis": {"grid": False}}
}
st.vega_lite_chart(vlt, use_container_width=True)
st.caption(
    f"Exception breakdown: {dict(zip(chart_labels, chart_values))} | "
    f"Reconciled (plain): {status_counts.get('Reconciled', 0)} | "
    f"Total: {total_chart}"
)

# ── Level 4: Verification ─────────────────────────────────────────────
_mr_acc = mr_overall.get("accuracy", 0)
_mr_fpr = mr_overall.get("false_positive_rate", 0)
_mr_fnr = mr_overall.get("false_negative_rate", 0)
_mr_mismatches = len(mr.get("mismatches", []))

st.markdown(
    f"""
    <div class="micro-label" style="margin-top: 1.8rem;">VERIFICATION</div>
    <div class="hcard" style="border-left-color: #4f8cff;">
      <div class="verify-block">
        <span class="verify-value">{_mr_acc:.0%}</span>
        <span class="verify-label">Classification accuracy</span>
      </div>
    </div>
    """,
    unsafe_allow_html=True,
)
st.caption(
    f"{_mr_mismatches} mismatches | False-positive rate {_mr_fpr:.2%} | "
    f"False-negative rate {_mr_fnr:.1%}"
)
st.caption(
    "Accuracy is a benchmark of classification correctness against this "
    "project's synthetic ground truth - labels generated from the same "
    "rule engine as the data, then corrected once by manual audit. Because "
    "generator and matcher share assumptions, 100% demonstrates internal "
    "consistency with that reference set (plus an external audit pass); it "
    "is not independent ground truth and not a claim about real-world "
    "financial accuracy."
)

# Match-rate gap explanation (from metrics_report.json)
if "match_rate_gap_note" in mr_overall:
    with st.expander("Why two match-rate numbers?", expanded=False):
        st.markdown(
            f"**Operational rate:** {mr_overall.get('match_rate_operational', 0):.2%} "
            f"({overall.get('reconciled_total', 0)}/{overall.get('total_cases', 0)} cases "
            f"resolved without human intervention)"
        )
        st.markdown(
            f"**Clean-match rate:** {mr_overall.get('match_rate_clean_no_exception', 0):.2%} "
            f"(cases with zero exception code in ground truth)"
        )
        st.markdown("---")
        st.caption(mr_overall["match_rate_gap_note"])

st.divider()

# ══════════════════════════════════════════════════════════════════════
# SECTION B: Case Explorer
# ══════════════════════════════════════════════════════════════════════
st.subheader("Case Explorer")

# Filter bar
fc1, fc2, fc3, fc4 = st.columns([1, 2, 2, 2])

with fc1:
    case_type_filter = st.selectbox(
        "Case type", ["All", "Orders", "Settlements"], index=0, key="f_type"
    )

with fc2:
    all_statuses = sorted(set(e["simplified_status"] for e in all_cases))
    status_filter = st.multiselect("Status", all_statuses, default=[], key="f_status")

with fc3:
    all_exceptions = sorted(
        set(e.get("exception_code") for e in all_cases if e.get("exception_code"))
    )
    exc_filter = st.multiselect("Exception code", all_exceptions, default=[], key="f_exc")

with fc4:
    search_text = st.text_input("Search case_id", placeholder="ord_... or set_...", key="f_search")

# Apply filters
filtered = all_cases[:]

if case_type_filter == "Orders":
    filtered = [e for e in filtered if e["case_type"] == "order"]
elif case_type_filter == "Settlements":
    filtered = [e for e in filtered if e["case_type"] == "settlement"]

if status_filter:
    filtered = [e for e in filtered if e["simplified_status"] in status_filter]

if exc_filter:
    filtered = [
        e
        for e in filtered
        if e.get("exception_code") and e["exception_code"] in exc_filter
    ]

if search_text.strip():
    q = search_text.strip().lower()
    filtered = [e for e in filtered if q in e["case_id"].lower()]

# Pagination
PAGE_SIZE = 25
total_pages = max(1, (len(filtered) + PAGE_SIZE - 1) // PAGE_SIZE)

page_col1, page_col2, page_col3 = st.columns([1, 1, 4])
with page_col1:
    page = st.number_input("Page", min_value=1, max_value=total_pages, value=1, key="f_page")
with page_col2:
    st.caption(f"of {total_pages} ({len(filtered)} cases)")

start = (page - 1) * PAGE_SIZE
page_cases = filtered[start : start + PAGE_SIZE]

# Table
if page_cases:
    # Build table data
    table_data = []
    for e in page_cases:
        table_data.append(
            {
                "case_id": e["case_id"],
                "Type": e["case_type"],
                "Status": e["simplified_status"],
                "Exception": e.get("exception_code") or "—",
                "Has explanation": "Yes" if e.get("explanation") else "—",
            }
        )
    df = pd.DataFrame(table_data)

    # Status color mapping using theme-consistent hex colors
    STATUS_HEX = {
        "Reconciled": "#00d2a0",
        "Reconciled (with note)": "#00d2a0",
        "Reconciled (no credit due)": "#00d2a0",
        "Needs Human Review": "#f5a623",
        "Unresolved": "#ff6b6b",
    }

    def _color_status(val):
        hex_color = STATUS_HEX.get(val, "#c8d6e5")
        return f"background-color: {hex_color}22; color: {hex_color}; font-weight: 600"

    styled = df.style.map(_color_status, subset=["Status"])
    st.dataframe(
        styled,
        use_container_width=True,
        hide_index=True,
        column_config={
            "Status": st.column_config.TextColumn(
                "Status",
                help="Reconciliation status",
            ),
        },
    )
else:
    st.info("No cases match the current filters.")

# Detail panel
st.markdown("---")
st.markdown("**Case Detail**")


# ── Case-detail rendering (DESIGN_PHASE10_CASE_EXPLORER.md) ──────────
_STATUS_PILLS = {
    "Reconciled": ("RECONCILED", "pill-green"),
    "Reconciled (with note)": ("RECONCILED WITH NOTE", "pill-green"),
    "Reconciled (no credit due)": ("NO CREDIT DUE", "pill-green"),
    "Needs Human Review": ("NEEDS REVIEW", "pill-amber"),
    "Unresolved": ("UNRESOLVED", "pill-red"),
}

_WHAT_TPL = {
    ("Reconciled", "order"): "Order {case_id} was reconciled: settlement credit matched and fully accounted for.",
    ("Reconciled", "settlement"): "Settlement {case_id} was reconciled: batch net matches bank credit.",
    ("Reconciled (with note)", "order"): "Order {case_id} was reconciled with a recorded note.",
    ("Reconciled (no credit due)", "settlement"): "Settlement {case_id} was reconciled: no bank credit was expected for this batch.",
    ("Needs Human Review", "order"): "Order {case_id} was flagged for human review.",
    ("Needs Human Review", "settlement"): "Settlement {case_id} was flagged for human review.",
    ("Unresolved", "order"): "Order {case_id} could not be matched to any settlement credit.",
    ("Unresolved", "settlement"): "Settlement {case_id} could not be reconciled.",
}

_ACTION_LINE = {
    "Reconciled": "No action needed.",
    "Reconciled (with note)": "No action needed.",
    "Reconciled (no credit due)": "No action needed.",
    "Needs Human Review": "Human review required.",
    "Unresolved": "Cannot currently be resolved automatically.",
}

_EV_ORDER = [
    ("settlement_ids", "Matched settlement(s)"),
    ("bank_utr", "Bank UTR (reference)"),
    ("order_residual", "Order residual amount"),
    ("refund_type", "Refund type"),
    ("ledger_refund_status", "Refund status in ledger"),
    ("settlement_refund_deduction", "Refund deduction in settlement"),
    ("settlement_gross_matched", "Settlement gross matched"),
    ("conflicting_amounts", "Conflicting amounts"),
    ("detail", "Note"),
]
_EV_SETTLEMENT = [
    ("bank_utr", "Bank UTR (reference)"),
    ("batch_net", "Batch net amount"),
    ("bank_amount", "Bank credit amount"),
    ("row_count", "Rows in batch"),
    ("diff", "Difference (net vs bank)"),
    ("ghost_order_ids", "Unmatched order IDs in batch"),
]

def _fmt_val(v):
    if v is None:
        return "Not applicable"
    if isinstance(v, bool):
        return "Yes" if v else "No"
    if isinstance(v, int):
        return f"{v:,}"
    if isinstance(v, float):
        return f"{v:,.2f}"
    return str(v)


def _ev_rows(v, label):
    if isinstance(v, list):
        if not v:
            return (
                f'<div class="evidence-row"><span class="ev-label">{_esc(label)}</span>'
                f'<span class="ev-value">None</span></div>'
            )
        out = []
        n = len(v)
        for j, val in enumerate(v):
            lab = label if j == 0 else f"{label} ({j + 1} of {n})"
            out.append(
                f'<div class="evidence-row"><span class="ev-label">{_esc(lab)}</span>'
                f'<span class="ev-value">{_esc(_fmt_val(val))}</span></div>'
            )
        return "".join(out)
    return (
        f'<div class="evidence-row"><span class="ev-label">{_esc(label)}</span>'
        f'<span class="ev-value">{_esc(_fmt_val(v))}</span></div>'
    )


def _render_case_detail(entry):
    cid = entry["case_id"]
    ctype = entry["case_type"]
    status = entry["simplified_status"]
    code = entry.get("exception_code")
    parts = ['<div class="detail-card">']

    # Header row: [case_id] [type] [status pill] [exception badge if any]
    pill_text, pill_cls = _STATUS_PILLS.get(status, ("", ""))
    parts.append(
        '<div class="detail-head">'
        f'<span class="ev-value" style="font-size:1.02rem;font-weight:700;color:#ffffff;">{_esc(cid)}</span>'
        f'<span class="ev-label" style="min-width:0;">{_esc(ctype)}</span>'
    )
    if pill_text:
        parts.append(f'<span class="pill {pill_cls}">{pill_text}</span>')
    if code:
        parts.append(f'<span class="badge">{_esc(code)}</span>')
    parts.append("</div>")

    # WHAT HAPPENED
    tpl = _WHAT_TPL.get((status, ctype))
    sentence = tpl.format(case_id=cid) if tpl else f"{ctype} {cid}: {status}."
    if code and code in _CODE_INFO:
        short = _CODE_INFO[code][0]
        if sentence.endswith("."):
            sentence = sentence[:-1] + f" ({short})."
        else:
            sentence = f"{sentence} ({short})."
    parts.append('<div class="ev-section micro-label">WHAT HAPPENED</div>')
    parts.append(f'<div class="what-line">{_esc(sentence)}</div>')

    # WHY
    parts.append('<div class="ev-section micro-label">WHY</div>')
    expl = entry.get("explanation")
    if expl:
        parts.append(
            '<div class="what-line" style="font-size:0.8rem;color:#8899b0;'
            'margin-bottom:0.2rem;">AI narration, Phase 3 - grounded in the case data below.</div>'
        )
        parts.append(f'<div class="what-line">{_esc(expl)}</div>')
    else:
        parts.append(
            '<div class="what-line">No AI narration exists for this case. It was '
            'classified by the deterministic reconciliation engine.</div>'
        )
        if code and code in _CODE_INFO:
            short, meaning = _CODE_INFO[code]
            parts.append(f'<div class="what-line">{_esc(short)} - {_esc(meaning)}</div>')

    # EVIDENCE
    parts.append('<div class="ev-section micro-label">EVIDENCE</div>')
    kf = entry.get("key_figures") or {}
    canon = _EV_ORDER if ctype == "order" else _EV_SETTLEMENT
    known = [k for k, _ in canon]
    row_html = []
    for k, label in canon:
        if k in kf:
            row_html.append(_ev_rows(kf[k], label))
    for k in sorted(set(kf) - set(known)):
        label = k.replace("_", " ").capitalize()
        row_html.append(_ev_rows(kf[k], label))
    parts.append("".join(row_html) if row_html else '<div class="what-line">None</div>')

    # NEXT STEP
    parts.append('<div class="ev-section micro-label">NEXT STEP</div>')
    parts.append(
        f'<div class="what-line">{_esc(_ACTION_LINE.get(status, "See case details."))}</div>'
    )
    sa = entry.get("suggested_action")
    if sa:
        if status == "Unresolved":
            parts.append('<div class="what-line">See suggested action below.</div>')
        parts.append(f'<div class="what-line">{_esc(sa)}</div>')

    # Optional: confidence note / soft flags (only when present)
    cn = entry.get("confidence_note")
    if cn:
        parts.append(
            f'<div class="what-line" style="color:#f5a623;margin-top:0.7rem;">'
            f'&#9888; Confidence note: {_esc(cn)}</div>'
        )
    flags = entry.get("soft_flags") or []
    if flags:
        parts.append('<div class="ev-section micro-label">Soft flags</div>')
        for fl in flags:
            parts.append(f'<div class="what-line" style="color:#f5a623;">&#9888; {_esc(fl)}</div>')

    parts.append("</div>")
    st.markdown("".join(parts), unsafe_allow_html=True)


detail_ids = [e["case_id"] for e in filtered]
if detail_ids:
    selected_id = st.selectbox("Select a case to inspect", detail_ids, index=0)
    selected = next((e for e in filtered if e["case_id"] == selected_id), None)

    if selected:
        with st.expander(f"{selected['case_id']} — {selected['simplified_status']}", expanded=True):
            _render_case_detail(selected)
else:
    st.info("No cases to display.")


st.divider()


# ══════════════════════════════════════════════════════════════════════
# SECTION C: Live Q&A
# ══════════════════════════════════════════════════════════════════════
st.subheader("Ask the Controller")
st.caption(
    "Questions are answered from this reconciliation run only - the "
    f"{overall.get('total_cases', 0):,} cases (orders, settlements, refunds, "
    "exceptions) shown above. Answers quote the same source data and "
    "explanations from this page, and each is checked against that data "
    "before it is displayed."
)

# Session state for conversation history
if "qa_history" not in st.session_state:
    st.session_state.qa_history = []

# ── Clear input BEFORE the widget renders (Streamlit rule: cannot
#    modify a widget's session_state key after the widget is created) ──
if st.session_state.get("_qa_clear_pending"):
    st.session_state["qa_input"] = ""
    st.session_state["_qa_clear_pending"] = False

# Clear history button (for demo reset)
if st.session_state.qa_history:
    if st.button("\U0001f5d1 Clear history", key="clear_history"):
        st.session_state.qa_history = []
        st.session_state["_qa_clear_pending"] = True
        st.rerun()

# Fixed-height scrollable container for conversation history
_qa_container = st.container(height=380)
with _qa_container:
    if st.session_state.qa_history:
        # Reverse chronological: most recent first
        for q_text, a_text, a_verified, a_fallback in reversed(
            st.session_state.qa_history
        ):
            with st.chat_message("user"):
                st.markdown(q_text)
            with st.chat_message("assistant"):
                if a_fallback == "api_error":
                    st.warning(a_text)
                else:
                    st.markdown(a_text)
                if a_verified:
                    st.caption("\u2713 Verified against source data")
                else:
                    st.caption("\u26a0 Figures not fully verified")
            # Tight gap within pair, wider gap between exchanges
            st.markdown("---")
    else:
        st.info("Ask a question about the reconciliation data above to get started.")

# Input: st.text_input + st.button (NOT st.chat_input)
# Root cause confirmed: st.chat_input causes auto-scroll on every load/rerun.
_q_col1, _q_col2 = st.columns([5, 1])
with _q_col1:
    question = st.text_input(
        "Ask about any order or settlement...",
        key="qa_input",
        label_visibility="collapsed",
    )
with _q_col2:
    ask_pressed = st.button("Ask", key="qa_submit")

if question and ask_pressed:
    # Call Q&A agent
    with st.spinner("Thinking..."):
        try:
            from qa_agent import answer_question

            result = answer_question(question)
        except Exception as e:
            result = {
                "answer": "I apologize -- the QA service encountered an error. Please try again.",
                "source_case_ids": [],
                "verified": False,
                "category": "out_of_scope",
                "fallback_reason": "api_error",
            }

    # Save to history, set flag to clear input on next run, then rerun
    st.session_state.qa_history.append(
        (
            question,
            result["answer"],
            result.get("verified", False),
            result.get("fallback_reason"),
        )
    )
    st.session_state["_qa_clear_pending"] = True
    st.rerun()

st.divider()


# ══════════════════════════════════════════════════════════════════════
# SECTION D: Engineering Story
# ══════════════════════════════════════════════════════════════════════
st.subheader("Engineering Story")

# Extract section 3 (the What Broke story) from audit_trail.md only
story_text = ""
try:
    # Find section 3 start
    s3_start = audit_text.find("## 3.")
    # Find section 4 start (only the story is shown here; the NEFT_FAILED
    # showcase and traced examples stay in audit_trail.md)
    s4_start = audit_text.find("## 4.")
    if s3_start >= 0 and s4_start > s3_start:
        story_text = audit_text[s3_start:s4_start].rstrip()
    elif s3_start >= 0:
        # Fallback: take from section 3 to end
        story_text = audit_text[s3_start:].rstrip()
    # Drop the numbered wrapper heading ("## 3. What Broke and How It Was Fixed")
    # so the expander shows only the story itself
    first_para_break = story_text.find("\n\n")
    if first_para_break >= 0:
        story_text = story_text[first_para_break:].lstrip("\n")
    # Drop any trailing horizontal rule left from the section separator
    if story_text.endswith("---"):
        story_text = story_text[:-3].rstrip()
except Exception:
    story_text = "*Could not load engineering story from audit_trail.md*"

with st.expander("What Broke and How We Fixed It", expanded=False):
    if story_text:
        st.markdown(story_text)
    else:
        st.info("Engineering story not available.")

st.divider()


# ══════════════════════════════════════════════════════════════════════
# SECTION E: Footer
# ══════════════════════════════════════════════════════════════════════
st.markdown("---")
st.caption("Built for Razorpay AI Buildathon | Track: AI Finance Controller")
st.caption(
    "Pipeline: 8 phases | 591 cases | 100% accuracy | "
    "96.1% reconciled | 3.9% transparently flagged"
)

# Hash provenance
hash_display = " | ".join(f"{k}: {v}" for k, v in hashes.items())
st.caption(f"Hash provenance: {hash_display}")
st.caption("Run: `streamlit run dashboard.py`")

